spring:
  application:
    name: eureka-discovery-service
    
server:
  port: 8092
eureka:
  client:
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8088/eureka   


