server:
  port: 8092
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka 

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: programVitor
        uri: lb://product-microservice
        predicates:
        - Path=/product/**
    
      
